version: "3.9" 
services:
  bot:
    build: .
    image: discord-bot
    restart: unless-stopped
    volumes:
      - ./downloads:/downloads:rw
      - ./queue:/queue:rw
      - ./voice_clients:/voice_clients:rw
